@baseurl=http://localhost:5001

###
# 获取所有数据
GET {{baseurl}}/db

###
# 初始化数据库
GET {{baseurl}}/initdb

###
# 备份
GET {{baseurl}}/backup

###
# 还原
GET {{baseurl}}/restore?v=1.0.0

###
# 启动 API 服务
POST {{baseurl}}/runServer
Content-Type: application/json

{
  "dbId": 1,
  "port": 3000
}

###
# 停止 API 服务
POST {{baseurl}}/stopServer
Content-Type: application/json

{
  "dbId": 1
}

###
# 检查端口是否被占用
GET {{baseurl}}/checkPortIsInUse?port=5001

###
# 上传文件
POST {{baseurl}}/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="logo.svg"
Content-Type: image/svg+xml

< /Users/andremao/git-repository/json-server-ui/src/assets/logo.svg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="logo.svg"
Content-Type: image/svg+xml

< /Users/andremao/git-repository/json-server-ui/src/assets/logo.svg

------WebKitFormBoundary7MA4YWxkTrZu0gW--


